[package]
name = "AutoDragFile"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
gtk = "0.18"
gtk-layer-shell = { version = "0.8", features = ["v0_6"] }
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.6"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
